### ISSUE TITLE
[建议]ChineseCalendar加上选项，不显示秒、不跳动时/分之间的冒号（示意秒）

### ISSUE THREAD

**Issue by retsyo** [chunmingwang/ChineseCalendar#1]
跳动的冒号太抢眼
有的时候也不需要精确到秒

谢谢

**Comment by chunmingwang** [comment]
了解, 建议收到

**Comment by chunmingwang** [comment]
Add: Show caption, Show second, Blink colon
https://github.com/chunmingwang/ChineseCalendar/commit/4721efac4ab239a1aa678e3e6ee6b2398fbc6aa3

**Comment by retsyo** [comment]
赞老兄的高效
