### ISSUE TITLE
[建议]拖动时间显示的区域时，拖动整个窗口位置

### ISSUE THREAD

**Issue by retsyo** [chunmingwang/ChineseCalendar#2]
当本程序窗口缩到比较小的时候，已经没法拖拽标题栏来在窗口内移动位置了
所以建议可以拖动时间显示的区域时，拖动整个窗口位置

**Comment by chunmingwang** [comment]
建议收到

**Comment by chunmingwang** [comment]
Add: Show caption, Show second, Blink colon
https://github.com/chunmingwang/ChineseCalendar/commit/4721efac4ab239a1aa678e3e6ee6b2398fbc6aa3
