### ISSUE TITLE
[建议]增加选项隐藏标题栏

### ISSUE THREAD

**Issue by retsyo** [chunmingwang/ChineseCalendar#3]
当整个窗口缩到比较小的时候，标题栏其实没有用途了
另请看 https://github.com/chunmingwang/ChineseCalendar/issues/2

**Comment by chunmingwang** [comment]
建议收到

**Comment by chunmingwang** [comment]
Add: Show caption, Show second, Blink colon
https://github.com/chunmingwang/ChineseCalendar/commit/4721efac4ab239a1aa678e3e6ee6b2398fbc6aa3
