### ISSUE TITLE
[bug?]隐藏caption，窗口最上方有白条

### ISSUE THREAD

**Issue by retsyo** [chunmingwang/ChineseCalendar#4]
如图
背景是cmd窗口，以便看得清白条
![QQ截图20231130110207](https://github.com/chunmingwang/ChineseCalendar/assets/7960913/1665a890-826f-40cc-bbd6-7f9362daa6fc)

**Comment by chunmingwang** [comment]
这是Windows隐藏Caption的显示效果
如果要完全没有, 需要用无边框窗口

> 如图 背景是cmd窗口，以便看得清白条

**Comment by chunmingwang** [comment]
![image](https://github.com/chunmingwang/ChineseCalendar/assets/35757455/6eb6eeef-6e13-4fe1-9e93-e2df6254d311)

![image](https://github.com/chunmingwang/ChineseCalendar/assets/35757455/68f6f46f-9772-4b65-9abf-7b9215fc84ed)

**Comment by chunmingwang** [comment]
如果需要更炫的效果, 需要用到GDIP的透明窗口, 用VB的版本有:

GDIP Analog Clock
![image](https://github.com/chunmingwang/ChineseCalendar/assets/35757455/234350e4-ceaf-444b-8c5f-72254b44fb29)

GDIP Digital Clock
![image](https://github.com/chunmingwang/ChineseCalendar/assets/35757455/8cc6d45f-b151-4378-8e76-86bf6cf5dcd2)

GDIP Text Clock
![image](https://github.com/chunmingwang/ChineseCalendar/assets/35757455/00977fec-9d7a-42f7-8029-1388ef81fd47)

Text Clock
![image](https://github.com/chunmingwang/ChineseCalendar/assets/35757455/1fc05d2b-efff-4c7e-ae24-0737b326976f)

Freebasic的正在学习UEZ的作品.

GDI+ Swiss Railway Clock
![image](https://github.com/chunmingwang/ChineseCalendar/assets/35757455/acd04ef5-84ad-4c67-a17f-eef57190278c)

Polar Clock
![image](https://github.com/chunmingwang/ChineseCalendar/assets/35757455/3c4104ec-15d1-41f7-b540-d68de46aa0e1)

**Comment by chunmingwang** [comment]
ChineseCalendar 是一个学习 VisualFBEditor 的范例, 不会做的很完美

**Comment by retsyo** [comment]
收到

**Comment by chunmingwang** [comment]
下次更新加一个无边框的选项

**Comment by chunmingwang** [comment]
Add None border option
https://github.com/chunmingwang/ChineseCalendar/commit/458087ade9873dc2cdf83dc4d4eed537e379cfc5
