### ISSUE TITLE
[bug]总在最前、长时间运行后时间不更新

### ISSUE THREAD

**Issue by retsyo** [chunmingwang/ChineseCalendar#5]
昨天、今天，用了2次，都碰到这个bug。同样的操作是：缩小界面放到右上角，设置总在最前。都摆放了超1小时。
昨天以为是偶发，今天又出现。而且今天再次拉大界面时，全黑了，没有显示数字。

先报告一下，我再看看能不能重现

**Comment by chunmingwang** [comment]
这个我也碰到过, 可能是Canvas或String有内存泄漏, 不过还没有最终找到原因.

**Comment by retsyo** [comment]
需要报给 https://github.com/XusinboyBekchanov/MyFbFramework 嘛？

**Comment by chunmingwang** [comment]
可以没问题

**Comment by chunmingwang** [comment]
谢谢你喜欢这个vfbe的例子，对于内存泄露，mff作者对canvas做了很多改善

**Comment by chunmingwang** [comment]
谢谢你喜欢这个vfbe的例子，对于内存泄露，mff作者对canvas做了很多改善

**Comment by chunmingwang** [comment]
谢谢你喜欢这个vfbe的例子，对于内存泄露，mff作者最近几天对canvas做了很多改善

**Comment by retsyo** [comment]
感谢

咱给自己的定位是用户，偶尔发现一些bug、提点建议。完善代码的事，就仰仗各位了

**Comment by chunmingwang** [comment]
我今天测试了一下新的mff, 发现新的canvas有一些问题, 不过gdip的内存泄漏视乎已经解决了.
啊凡达觉得你也应该参与vfbe和mff, 多谢人参与共同完善

**Comment by retsyo** [comment]
我现在较少用BASIC语言了。早过了激情燃烧、万事手搓的年龄；作为非IT工作者，讲求使用快速、实用、适用的工具。因为
- 1. 平时经常处理的数据类型，是字符串。越使用python的索引/切片、函数级联这样的操作，越不喜欢BASIC这种古董语言的方法（函数名放最前面），写着累、看着也累。
- 2. 处理多的，是WORD、EXCEL文件。freebasic除了通过COM，几乎没法读写
- 3. 即便freebasic通过COM读了EXCEL文件，也没有python的pandas那样的处理库

是的，以上2、3可以通过写库解决。但是这2个库，都是大工程，不是单枪匹马可以完成的。社区发展这么多年，无人提及，也就意味着大家没有这方面的需求。

2个拭目以待
- 1. [论坛帖子](https://www.freebasic.net/forum/viewtopic.php?t=32254) 中 coderJeff 提到1.20版本的开发，他要关注开发真的项目，而不是单纯freebasic自身。不知道这是不是freebasic官方想法。很可惜，freebasic诞生的目的只是为了再生QBASIC；逐步发展出了一些新功能；但是基本长期上踯躅不前。前期错过了开发稍微大一点的项目、提供给用户使用，然后用户找bug、提意见的发展过程。不知现在还能不能迎头赶上。
- 2. mff中，使用webview2进行GUI开发。最好多数操作直接freebasic写完，而不借助Javascript。

别误会
- 1. 我认为软件测试、提需求、提bug，也是对软件发展的有益环节。请别归为“找茬”
- 2. 工具/软件/库，越多人用，越可能暴露问题，越可能快速发展；否则只是自娱自乐的玩具。python的numpy、nicegui之类我也在边用、边提bug，甚至自己提交补丁。但是底层去修补freebasic、mff，现在不是我的精力所允许的。

再次感谢

**Comment by chunmingwang** [comment]
能说出这么的感想, 至少说明你是关注fb, vfbe的.

**Comment by chunmingwang** [comment]
mff Canvas显示区域和绘画区域大小不一致的问题, 问题反馈后也解决了
